id: ICF9364A3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T12:30:34+00:00'
last_modified: '2022-06-15T16:56:07.797996+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23624
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་བླ་མ་རིག་འཛིན་འདུས་པའི་གདང་རོལ་ཉུང་ངུ་བློ་གསལ་མགུལ་རྒྱན་གཏོར་མའི་དཔེའུ་རིས་བཅས་དང་པད་གླིང་གི་དབྱངས་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    82D4:
      image_group_id: I3200
      title: ''
      total_pages: 86
      order: 1
      base_file: 82D4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
